const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.HTMLElement,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.ScriptsInEvents.EventSheet1_Event1_Act6,
		C3.ScriptsInEvents.EventSheet1_Event1_Act7,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Exps.Text
	];
};
self.C3_JsPropNameTable = [
	{LocalStorage: 0},
	{LEDX: 0},
	{Defib: 0},
	{Bitcoin: 0},
	{Mouse: 0},
	{Button: 0},
	{Text: 0},
	{TiledBackground: 0},
	{Temp: 0},
	{Touch: 0},
	{Killa: 0},
	{BitcoinPrice: 0},
	{Wiki: 0},
	{Browser: 0},
	{Audio: 0},
	{KillaBody: 0},
	{Name1: 0},
	{Name2: 0},
	{Settings: 0},
	{SettingsHitbox: 0},
	{Sprite: 0},
	{TempTextBTC: 0},
	{HTMLElement: 0},
	{TextInput: 0},
	{TextInput2: 0},
	{Button2: 0},
	{settingsVisible: 0},
	{btcPriceRub: 0}
];

self.InstanceType = {
	LocalStorage: class extends self.IInstance {},
	LEDX: class extends self.ISpriteInstance {},
	Defib: class extends self.ISpriteInstance {},
	Bitcoin: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Button: class extends self.IButtonInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Temp: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Killa: class extends self.ISpriteInstance {},
	BitcoinPrice: class extends self.ISpriteInstance {},
	Wiki: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	KillaBody: class extends self.ISpriteInstance {},
	Name1: class extends self.ITextInstance {},
	Name2: class extends self.ITextInstance {},
	Settings: class extends self.ISpriteInstance {},
	SettingsHitbox: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TempTextBTC: class extends self.ITextInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	TextInput: class extends self.ITextInputInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	Button2: class extends self.IButtonInstance {}
}